apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keep-postgres
  namespace: {{.Release.Namespace}}
spec:
  refreshPolicy: CreatedOnce
  target:
    name: keep-postgres
    template:
      engineVersion: v2
      type: Opaque
      data:
        username: "keep"
        database: "keep"
        password: "{{ `{{ .password }}` }}"
        connection_string: "postgresql://keep:{{ `{{ .password }}` }}@groundcover-postgresql:5432/keep"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: gc-gen
      rewrite:
        - regexp:
            source: "^password$"
            target: "password"
