apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: groundcover-token
  namespace: groundcover
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: groundcover-token
  dataFrom:
    - extract:
        key: {{.Values.groundcoverTokenAwsSecret}}
