apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: groundcover-clickhouse
  namespace: {{.Release.Namespace}}
spec:
  refreshPolicy: CreatedOnce
  target:
    name: groundcover-clickhouse
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        admin-password: "{{ `{{ .password }}` }}" # escaped because ExternalSecret is rendered by Helm
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: gc-gen
