db:
  # TODO: make cnpg optional
  image: ghcr.io/cloudnative-pg/postgresql:17.7-minimal-trixie
  storageClass: ebs-gp3-encrypted
replicas: 1
image:
  version: b4bbecd-0000-gb4bbecd # staging_services/go-backend
ingress:
  traefik:
    hostname: go-backend-helm-traefik.staging.kubestarterkit.com
gateway:
  traefik:
    hostname: gateway-traefik-helm.staging.kubestarterkit.com
