db:
  # TODO: make cnpg optional
  image: ghcr.io/cloudnative-pg/postgresql:17.5
  storageClass: ebs-gp3-encrypted
replicas: 1
image:
  version: addbaaa-0000-gaddbaaa # staging_services/go-backend
ingress:
  traefik:
    hostname: go-backend-helm-traefik.staging.kubestarterkit.com
