db:
  # TODO: make cnpg optional
  image: ghcr.io/cloudnative-pg/postgresql:17.5
  storageClass: ebs-gp3-encrypted
replicas: 1
image:
  version: 0.2.1-0070-gd8b12f1 # staging_services/go-backend
ingress:
  traefik:
    hostname: go-backend-helm-traefik.staging.kubestarterkit.com
