db:
  # TODO: make cnpg optional
  image: ghcr.io/cloudnative-pg/postgresql:17.7-minimal-trixie
  storageClass: ebs-gp3-encrypted
replicas: 1
image:
  version: 9c6832f-0000-g9c6832f # staging_services/go-backend
ingress:
  traefik:
    hostname: go-backend-helm-traefik.staging.kubestarterkit.com
    clusterIssuer: letsencrypt-prod-dns
    # tlsSecretName: optional, defaults to hostname with dots replaced by dashes + "-tls"
gateway:
  traefik:
    hostname: gateway-traefik-helm.staging.kubestarterkit.com
