db:
  # TODO: make cnpg optional
  image: dhi.io/postgres:17-alpine3.22
  storageClass: ebs-gp3-encrypted
replicas: 1
image:
  version: 0.3.0-0000-gd08aef3 # staging_services/go-backend
ingress:
  traefik:
    hostname: go-backend-helm-traefik.staging.kubestarterkit.com
