apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-istio
  annotations:
    external-dns.alpha.kubernetes.io/hostname: staging.kubestarterkit.com
spec:
  ingressClassName: istio
  rules:
    - host: "staging.kubestarterkit.com"
      http:
        paths:
          - path: /ingress-istio
            pathType: ImplementationSpecific
            backend:
              service:
                name: nginx-clusterip
                port:
                  number: 8080
