apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-traefik
  namespace: {{.Release.Namespace}}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.traefik.hostname }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.ingress.traefik.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-backend
                port:
                  number: 8080
