apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  annotations:
    kargo.akuity.io/color: avocado
  name: production-go-backend
  namespace: kargo-kube-starter-kit
spec:
  promotionTemplate:
    spec:
      steps:
        - task:
            name: no-op
  requestedFreight:
    - origin:
        kind: Warehouse
        name: services--go-backend
      sources:
        direct: false
        stages:
          - semver-gate-go-backend
