applications:
  # Could specify path for each application here to make it more flexible
  argocd:
    enabled: true
  cert-manager:
    enabled: true
  cloudnative-pg:
    enabled: true
  datadog-operator:
    enabled: false
  ebs-csi-driver-resources:
    enabled: true
  envoy-gateway:
    enabled: false
  external-dns:
    enabled: true
  external-secrets:
    enabled: true
  gateway-api-crds:
    enabled: true
  karpenter:
    enabled: true
  reloader:
    enabled: true
  signoz-k8s-infra:
    enabled: true
  traefik:
    enabled: true
    # Gateway certificateRefs get default group/kind added by the API server
    ignoreDifferences:
      - group: gateway.networking.k8s.io
        kind: Gateway
        jsonPointers:
          - /spec/listeners/1/tls/certificateRefs/0/group
          - /spec/listeners/1/tls/certificateRefs/0/kind
