gateway-helm:
  topologyInjector:
    annotations:
      # Prevents noisy diffs for caBundle which gets updated frequently by certGen helm hook job
      kluctl.io/ignore-diff-field: "webhooks[0].clientConfig.caBundle"

gateway-crds-helm:
  crds:
    gatewayAPI:
      enabled: true
    # Do we want the envoy specific CRDs?
    # envoyGateway:
    #   enabled: true
