apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-dex
  namespace: argocd
  labels:
    # Necessary to use argo secret referencing in dex config
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: github-dex
  dataFrom:
    - extract:
        key: ksk-use2-staging-eks-argocd-github-dex
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
