[tasks.bootstrap-plan]
description = "Terragrunt plan for global bootstrapping"
dir = "global/bootstrapping"
run = "terragrunt run plan"

[tasks.bootstrap-apply]
description = "Terragrunt apply for global bootstrapping"
dir = "global/bootstrapping"
run = "terragrunt run apply"

[tasks.plan-all]
description = "Terragrunt plan across all modules"
run = "terragrunt run --all plan"
