version: "3"

tasks:
  deploy-staging:
    desc: "Deploy kluctl infrastructure staging target"
    cmds:
      # - kluctl helm-pull
      - kluctl deploy -t staging-us-east-2 --prune

  helm-pull:
    cmds:
      - kluctl helm-pull
