apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: ambient
  revision: 1-27-1
  values:
    defaultRevision: 1-27-1
    pilot:
      env:
        ISTIOD_CUSTOM_HOST: "istiod-1-27-1.istio-system.svc,istiod-1-27-1.istio-system.svc.cluster.local"
