apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: go-backend-kustomize.local.kubestarterkit.com
spec:
  rules:
    - host: "go-backend-kustomize.local.kubestarterkit.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-backend
                port:
                  number: 8080
