apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik
  annotations:
    external-dns.alpha.kubernetes.io/hostname: gateway-traefik-kustomize.production.kubestarterkit.com
spec:
  hostnames:
    - gateway-traefik-kustomize.production.kubestarterkit.com
