apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ingress-traefik-kustomize.production.kubestarterkit.com
spec:
  tls:
    - hosts:
        - ingress-traefik-kustomize.production.kubestarterkit.com
      secretName: ingress-traefik-kustomize-tls
  rules:
    - host: "ingress-traefik-kustomize.production.kubestarterkit.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-backend
                port:
                  number: 8080
