apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: go-backend-pg
  namespace: apps
spec:
  instances: 1
  storage:
    size: 1Gi
    storageClass: {{goBackend.db.storageClass}}
  superuserSecret:
    name: go-backend-db-superuser
  # TODO: ensure this matches the local postgres version
  image: {{goBackend.db.image}}
