apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: infrastructure
  namespace: kluctl-gitops
spec:
  interval: 5m
  source:
    git:
      url: git@github.com:DevOps-Directive/kube-starter-kit.git
      path: kubernetes/kluctl/infrastructure
      # ref:
      #   branch: <NON_DEFAULT_BRANCH>
  credentials:
    git:
      - host: github.com
        secretRef:
          name: deploy-key
  target: {{args.cluster_name}}
  args:
    # this passes the cluster_name initially passed via `kluctl deploy -a cluster_name=xxx.example.com` into the KluctlDeployment
    cluster_name: {{args.cluster_name}}
  context: default
  # prune: true
  prune: false
  delete: true
