{{- range $name, $config := .Values.applications }}
{{- if $config.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: kubernetes/rendered/{{ $.Values.cluster }}/infrastructure/{{ $name }}
    repoURL: git@github.com:DevOps-Directive/kube-starter-kit.git
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - SkipDryRunOnMissingResource=true
{{- end }}
{{- end }}