values:
  db:
    # TODO: make cnpg optional
    image: ghcr.io/cloudnative-pg/postgresql:17.7-minimal-trixie
    storageClass: ebs-gp3-encrypted
  replicas: 1
  image:
    tag: addbaaa-0000-gaddbaaa # staging_services/go-backend
