values:
  db:
    # TODO: make cnpg optional
    image: ghcr.io/cloudnative-pg/postgresql:17.7-minimal-trixie
    storageClass: ebs-gp3-encrypted
  replicas: 1
  image:
    tag: 9c6832f-0000-g9c6832f # staging_services/go-backend
