values:
  db:
    storageClass: standard
  image:
    tag: local-version
  ingress:
    nginx:
      hostname: go-backend-timoni.172-20-0-100.sslip.io
    traefik:
      hostname: go-backend-timoni.172-20-0-101.sslip.io
