values:
  db:
    # TODO: make cnpg optional
    image: ghcr.io/cloudnative-pg/postgresql:17.7-minimal-trixie
    storageClass: ebs-gp3-encrypted
  replicas: 1
  image:
    tag: 31fa9ba-0000-g31fa9ba # staging_services/go-backend
