values:
  db:
    # TODO: make cnpg optional
    image: dhi.io/postgres:17-alpine3.22
    storageClass: ebs-gp3-encrypted
  replicas: 1
  image:
    tag: ceac01b-0000-gceac01b # staging_services/go-backend
