[tools]
# Inherits from ancestor mise.toml files

[env]
IMAGE_REPO = "857059614049.dkr.ecr.us-east-2.amazonaws.com/services/container-only-dummy"
IMAGE_TAG = "foobarbaz"
SERVICE_RELEASE_TAG = "services/container-only-dummy"
