apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: production--kubestarterkit--com
spec:
  commonName: production.kubestarterkit.com
  dnsNames:
    - production.kubestarterkit.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-dns
  secretName: production--kubestarterkit--com
