# This is the entrypoint (which manages all of the other applications in this chart)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-app-of-apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: kubernetes/rendered/{{ .Values.cluster }}/argocd/infrastructure
    repoURL: git@github.com:DevOps-Directive/kube-starter-kit.git
    # TODO: set to main
    targetRevision: sp/app-of-apps
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
