---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  sources:
    # helm/oci repo (1st party ECR or external)
    - chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 1.16.1
      helm:
        releaseName: sealed-secrets
        valueFiles:
          - $values/codefresh-build-1.yml
    # Separate git repo containing values file (this would reference kube-starter-kit repo)
    - repoURL: https://github.com/codefresh-io/yaml-examples.git
      targetRevision: master
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
