apiVersion: v1
data:
  sshPrivateKey: <b64 encoded private key>
  type: Z2l0
  url: Z2l0QGdpdGh1Yi5jb206RGV2T3BzLURpcmVjdGl2ZS9rdWJlLXN0YXJ0ZXIta2l0LmdpdA==
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-2591551873
  namespace: argocd
type: Opaque
