version: "3"

vars:
  GREETING: Hello, World!

tasks:
  # TODO: move these to gitops model
  install-karpenter:
    cmds:
      - helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version 1.7.1 --values karpenter-values.yaml
    silent: true

  install-external-secrets-operator:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
