version: "3"

tasks:
  install:
    cmds:
      - |
        helm repo add external-secrets https://charts.external-secrets.io
        helm repo update
        helm install external-secrets \
          external-secrets/external-secrets \
          --version 0.20.2 \
          --namespace external-secrets \
          --create-namespace \
          --values values.yaml

  apply-resources:
    cmds:
      - kubectl apply -f ./resources
