# Chart dependency versions for staging
# chartVersions:
#   argo-cd: ""

environment: staging

ingress:
  hostname: argocd.staging.kubestarterkit.com

argo-cd:
  configs:
    cm:
      # NOTE: This duplicates the hostname above, but can't be derived from it
      # because Helm doesn't support templating within values files and this
      # value is passed to the ArgoCD sub-chart
      url: https://argocd.staging.kubestarterkit.com
