apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  annotations:
    kargo.akuity.io/color: salmon
  name: staging-go-backend-no-migrations
  namespace: kargo-kube-starter-kit
spec:
  promotionTemplate:
    spec:
      steps:
        - task:
            name: update-image
          vars:
            - name: image
              value: 857059614049.dkr.ecr.us-east-2.amazonaws.com/services/go-backend-no-migrations
            - name: updateImagePath
              value: ./src/kubernetes/kluctl/apps/go-backend-no-migrations/Deployment.go-backend.yaml
  requestedFreight:
    - origin:
        kind: Warehouse
        name: services--go-backend-no-migrations
      sources:
        direct: true
        stages: []
