api:
  adminAccount:
    passwordHash: $2y$10$qGWGTVcHr6UGo0NPxp2yzewdOCf7bmNNcCq6azfALDn6sa4/zPXra
    tokenSigningKey: 6uWpb4Qohkv87SX3E8O6ViZDW5GfNVGY
  host: kargo.staging.kubestarterkit.com
  tls:
    enabled: false
    terminatedUpstream: true
  ingress:
    enabled: true
    ingressClassName: nginx
    tls:
      selfSignedCert: false # provisioning a real cert with cert-manager
  oidc:
    enabled: true
    additionalScopes:
      - groups
    admins:
      claims:
        # name:
        #   - sidpalas
        groups:
          - DevOps-Directive:admins
    # users:
    #   claims:
    #     name:
    #       - sidpalas
    dex:
      enabled: true
      env:
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-dex
              key: clientSecret
      # Adapted from: https://dexidp.io/docs/connectors/github/
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: Ov23liYEC6qc8sjOLJA6
            clientSecret: $CLIENT_SECRET # Best not to include secrets in your values.yaml (load as env var from secret)
            redirectURI: https://kargo.staging.kubestarterkit.com/dex/callback # use this as Authorization callback URL in GitHub Oauth App
            orgs: # Limit access to users in specific orgs; optional but recommended
              - name: DevOps-Directive
