apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: go-backend-pg
  namespace: apps
spec:
  instances: 1
  storage:
    size: 1Gi
    # TODO:  template this
    # storageClass: ebs-gp3-encrypted
    storageClass: standard
  superuserSecret:
    name: go-backend-db-superuser
  # TODO: ensure this matches the local postgres version
  image: ghcr.io/cloudnative-pg/postgresql:17.5
