apiVersion: v2
name: groundcover-wrapper
description: Umbrella chart that installs groundcover plus extra resources
type: application
version: 0.1.0

dependencies:
  - name: groundcover
    repository: "https://helm.groundcover.com"
    version: 1.11.61
