apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ingress-nginx-kustomize.staging.kubestarterkit.com
spec:
  ingressClassName: nginx
  rules:
    - host: "ingress-nginx-kustomize.staging.kubestarterkit.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-backend
                port:
                  number: 8080
