apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-istio
  annotations:
    external-dns.alpha.kubernetes.io/hostname: minimal-istio.staging.kubestarterkit.com
spec:
  ingressClassName: istio
  rules:
    - host: minimal-istio.staging.kubestarterkit.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: go-backend
                port:
                  number: 8080
