apiVersion: v1
kind: Service
metadata:
  name: go-backend
spec:
  type: ClusterIP
  selector:
    app: go-backend
  ports:
    - protocol: TCP
      port: 8080 # Port the service is listening on
      targetPort: 8080 # Port the container is listening on (if unset, defaults to equal port value)
