apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: signoz-apikey
  namespace: {{.Release.Namespace}}
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: signoz-apikey
  dataFrom:
    - extract:
        key: {{.Values.signozApiKeyAwsSecret}}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
