name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      spec:
        required: true
      run_name:
        required: false

run-name: "${{inputs.run_name}}"

jobs:
  digger-job:
    runs-on: ubuntu-24.04
    env:
      AWS_REGION: us-east-2
    permissions:
      contents: write # required to merge PRs
      actions: write # required for plan persistence
      id-token: write # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      issues: read # required to check if PR number is an issue or not
      statuses: write # required to validate combined PR status

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::094905625236:role/ksk-gbl-infra-bootstrap-github-oidc
      - name: ${{ fromJSON(github.event.inputs.spec).job_id }}
        run: echo "job id ${{ fromJSON(github.event.inputs.spec).job_id }}"
      - uses: diggerhq/digger@869b24dc6797a24927db6c80af5aaff74be3911f # v0.6.127 + digger-version input
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          digger-spec: ${{ inputs.spec }}
          setup-terraform: true
          terraform-version: 1.13.3
          setup-terragrunt: true
          terragrunt-version: 0.90.0
          upload-plan-destination: aws
          upload-plan-destination-s3-bucket: kube-starter-kit-tf-digger-plans
          cache-dependencies: true
          digger-version: v0.6.127
          reporting-strategy: "latest_run"

          # setup-opentofu: true
          # opentofu-version: 1.10.3
          # Could set up AWS here instead... (it uses the aws setup action under the hood)
          # setup-aws: true
          # aws-region: ${{ env.AWS_REGION }}
          # aws-role-to-assume: arn:aws:iam::094905625236:role/github-oidc-admin
