name: octo-test

on:
  push:
    branches:
      - sp/octo-sts-gh-permissions

jobs:
  digger-job:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write # required for workload-identity-federation

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: octo-sts/action@d6c70ad3b9ac85df6da6b9749014d7283987cfec # v1.0.3
        id: octo-sts
        with:
          scope: DevOps-Directive/kube-starter-kit
          identity: digger # see .github/chainguard/digger.sts.yaml for trust policy
