name: Scheduled Terraform Drift Detection + Reconciliation

on:
  workflow_dispatch:
  # schedule:
  # Run this workflow at the top of every hour
  # - cron: "0 9-20 * * 1-5"

jobs:
  drift-detection:
    name: Detect and reconcile drift in Terraform stacks
    runs-on: ubuntu-24.04
    env:
      AWS_REGION: us-east-2
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      checks: read

    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      ### Install tooling
      - name: Install Terramate
        uses: terramate-io/terramate-action@0500f8a40b57a793a41edd2aea0a49e31c7204e8 # v3.2.0
        with:
          version: "0.15.1"
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "1.14.3"
          terraform_wrapper: false

      ### Restore provider cache
      - name: Restore Terraform provider cache
        uses: actions/cache/restore@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ${{ github.workspace }}/.tf_plugin_cache_dir
          key: terraform-providers-${{ hashFiles('terraform/live/**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-providers-

      ### Configure cloud credentials
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::094905625236:role/ksk-gbl-infra-bootstrap-github-oidc
      - name: Verify AWS credentials
        run: aws sts get-caller-identity
      - name: Get GitHub token via octo-sts
        uses: octo-sts/action@d6c70ad3b9ac85df6da6b9749014d7283987cfec # v1.0.3
        id: octo-sts
        with:
          scope: DevOps-Directive/kube-starter-kit
          identity: terramate # see .github/chainguard/terramate.sts.yaml for trust policy

      ### Run Dift Check
      - name: Run Terraform init in all stacks
        run: |
          terramate script run \
            -C terraform/live \
            --parallel 1 \
            init
        env:
          TF_VAR_github_token: ${{ steps.octo-sts.outputs.token }}

      - name: Run drift detection
        id: drift-detect
        run: |
          terramate script run \
            -C terraform/live \
            --parallel 5 \
            --continue-on-error \
            -- \
            drift detect
        env:
          TF_VAR_github_token: ${{ steps.octo-sts.outputs.token }}

      - name: Check for auto reconcile
        id: find-drifted
        run: |
          terramate list \
            --status=drifted \
            --tags reconcile

      - name: Run drift reconciliation
        id: drift-reconcile
        if: steps.find-drifted.outputs.stdout
        run: |
          terramate script run \
            -C terraform/live \
            --tags reconcile \
            --status=drifted \
            --parallel 5 \
            --continue-on-error \
            -- \
            drift reconcile
        env:
          TF_VAR_github_token: ${{ steps.octo-sts.outputs.token }}
