apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: go-backend-pg
  namespace: apps
spec:
  instances: 1
  storage:
    size: 1Gi
    storageClass: OVERRIDE_ME
  superuserSecret:
    name: go-backend-db-superuser
  image: ghcr.io/cloudnative-pg/postgresql:17.5
